"""Content-addressed release identity, independent of installation and data paths."""

from __future__ import annotations

import hashlib
import importlib.metadata
import json
import platform
import re
import sys
from importlib.resources import files
from pathlib import Path
from typing import TYPE_CHECKING, Any

from packaging.requirements import Requirement
from packaging.version import Version

if TYPE_CHECKING:
    from .config import Settings


def file_sha256(path: str | Path) -> str:
    source = Path(path)
    return hashlib.sha256(source.read_bytes()).hexdigest() if source.is_file() else "missing"


def package_root() -> Path:
    return Path(__file__).resolve().parent.parent


def code_fingerprint() -> str:
    """Hash executable code and browser assets, excluding generated bytecode/metadata."""
    digest = hashlib.sha256()
    root = package_root()
    for path in sorted(root.rglob("*")):
        if not path.is_file() or (
            path.suffix not in {".py", ".css", ".js", ".html"} and path.name != "py.typed"
        ):
            continue
        digest.update(path.relative_to(root).as_posix().encode())
        digest.update(path.read_bytes())
    return digest.hexdigest()


def build_metadata() -> dict[str, Any]:
    resource = files(__package__.split(".")[0]).joinpath("build-info.json")
    if resource.is_file():
        return json.loads(resource.read_text(encoding="utf-8"))
    root = package_root().parent
    if not (root / "pyproject.toml").is_file():
        root = root.parent
    return {
        "runtime_requirements": [
            line.rstrip("\\").strip()
            for line in (root / "requirements.lock").read_text(encoding="utf-8").splitlines()
            if re.match(r"^[A-Za-z0-9][A-Za-z0-9._-]*(?:\[[^]]+\])?==", line)
        ],
        "dependency_lock_fingerprints": {
            name: file_sha256(root / name)
            for name in ("uv.lock", "requirements.lock", "build-requirements.lock")
        },
        "code_fingerprint": code_fingerprint(),
    }


def prompt_fingerprint() -> str:
    digest = hashlib.sha256()
    root = package_root()
    for relative in (
        "application/query_prompt.py",
        "application/context_rendering.py",
        "infrastructure/ollama_generator.py",
    ):
        digest.update(relative.encode())
        digest.update((root / relative).read_bytes())
    return digest.hexdigest()


def _runtime_requirements() -> list[Requirement]:
    declarations = build_metadata().get("runtime_requirements")
    if not isinstance(declarations, list) or not declarations:
        raise ValueError("build identity has no runtime dependency inventory")
    requirements: list[Requirement] = []
    names: set[str] = set()
    for declaration in declarations:
        if not isinstance(declaration, str):
            raise ValueError("runtime inventory entries must be requirement strings")
        requirement = Requirement(declaration)
        pins = list(requirement.specifier)
        if requirement.url or len(pins) != 1 or pins[0].operator != "==" or "*" in pins[0].version:
            raise ValueError("runtime dependency inventory must contain exact versions")
        if requirement.marker is not None and not requirement.marker.evaluate():
            continue
        name = re.sub(r"[-_.]+", "-", requirement.name).lower()
        if name in names:
            raise ValueError("runtime dependency inventory contains duplicate active packages")
        names.add(name)
        requirements.append(requirement)
    return requirements


def dependency_versions() -> dict[str, str]:
    """Attest all locked runtime packages applicable to this host, not a shortlist."""
    versions: dict[str, str] = {}
    for requirement in _runtime_requirements():
        package = re.sub(r"[-_.]+", "-", requirement.name).lower()
        try:
            versions[package] = importlib.metadata.version(package)
        except importlib.metadata.PackageNotFoundError:
            versions[package] = "missing"
    return versions


def runtime_dependency_errors() -> list[str]:
    """Refuse production when installed runtime packages differ from the build lock."""
    try:
        requirements = _runtime_requirements()
        installed = dependency_versions()
        errors = []
        for requirement in requirements:
            name = re.sub(r"[-_.]+", "-", requirement.name).lower()
            actual = installed[name]
            expected = next(iter(requirement.specifier)).version
            if actual == "missing" or Version(actual) != Version(expected):
                errors.append(f"runtime dependency {name} must match locked version {expected}")
        return errors
    except (OSError, ValueError, TypeError, KeyError) as exc:
        return [f"runtime dependency inventory invalid: {type(exc).__name__}"]


def release_identity(config: Settings) -> dict[str, Any]:
    metadata = build_metadata()
    return {
        "app_revision": config.app_revision,
        "python_runtime": {
            "implementation": sys.implementation.name,
            "version": platform.python_version(),
            "platform": sys.platform,
            "machine": platform.machine(),
        },
        "llm_model": config.llm_model,
        "llm_model_digest": config.llm_model_digest,
        "embedding_model": config.embedding_model,
        "embedding_model_digest": config.embedding_model_digest,
        "prompt_fingerprint": prompt_fingerprint(),
        "code_fingerprint": code_fingerprint(),
        "security_fingerprint": security_fingerprint(config),
        "dependency_versions": dependency_versions(),
        "dependency_lock_fingerprints": metadata["dependency_lock_fingerprints"],
    }


def security_fingerprint(config: Settings) -> str:
    """Bind public connection identity and query policy without exposing secrets."""
    public_keys = {
        "driver",
        "server",
        "database",
        "uid",
        "user id",
        "encrypt",
        "trustservercertificate",
        "authentication",
    }
    target = {
        item.group(1).strip().lower(): item.group(2).strip().strip("{}")
        for item in re.finditer(r"(?:^|;)\s*([^=;]+)=((?:\{[^}]*\})|[^;]*)", config.mssql_conn_str)
        if item.group(1).strip().lower() in public_keys
    }
    policy = {
        name: getattr(config, name)
        for name in (
            "sql_allowed_schemas",
            "sql_allowed_tables",
            "sql_denied_tables",
            "sql_denied_columns",
            "sql_aggregation_only_tables",
            "sql_allow_select_star",
            "sql_allow_cross_join",
            "sql_require_table",
            "sql_max_joins",
            "sql_max_subqueries",
            "max_result_rows",
            "llm_num_ctx",
            "llm_num_predict",
            "prompt_feedback_examples",
            "table_retrieval_token_budget",
            "table_retrieval_require_calibration",
            "eval_min_pass_rate",
            "eval_min_positive_pass_rate",
            "eval_min_refusal_pass_rate",
            "eval_min_semantic_ir_pass_rate",
            "eval_min_execution_pass_rate",
            "eval_min_retrieval_recall",
            "production_eval_min_cases",
            "production_eval_min_positive_cases",
            "production_eval_min_refusal_cases",
            "production_retrieval_calibration_min_cases",
            "production_retrieval_test_min_cases",
        )
    }
    return hashlib.sha256(
        json.dumps({"target": target, "policy": policy}, sort_keys=True).encode()
    ).hexdigest()
